webcrumbs-community/webcrumbs

component-library/components/Button/Button.css, component-library/components/Button/Button.js, component-library/components/Button/index.js, component-library/components/TextInput/TextInput.css, component-library/components/TextInput/TextInput.js, component-library/components/TextInput/index.js, component-library/index.js
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
Added Button and TextIput components in React.
6
- [- -] New feature (non-breaking change which adds functionality)
I tested with using index.js file  to import the components
- [= ] My code follows the style guidelines of this project
- [ =] I have performed a self-review of my own code
- [ =] I have commented my code, particularly in hard-to-understand areas
- [= ] I have made corresponding changes to the documentation
- [ =] My changes generate no new warnings
- [ =] Any dependent …
=> Added component library

README.md
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
=> Add contributors avatars to Readme #43

.gitignore
=> Gitignore .vscode and logs

component-library/components/TextInput/TextInput.css, temp.md
Fix minor issues in the docs.
N/A
=> Fix typos in temp.md

README.md, demo/pages/home/home.module.css, demo/pages/home/index.tsx, demo/styles/Home.module.css
We have implemented the required UI (following the rough template mention in the issue #68)
We have not completely followed the conventions (used the inline css), but we will improve the code to follow the conventions to keep the codebase uniform.
=> UI Frontend issue #68

plugins/clerk-auth/.babelrc, plugins/clerk-auth/.env.example, plugins/clerk-auth/.gitignore, plugins/clerk-auth/package-lock.json, plugins/clerk-auth/package.json, plugins/clerk-auth/public/index.html, plugins/clerk-auth/src/App.jsx, plugins/clerk-auth/src/Welcome.jsx, plugins/clerk-auth/src/index.jsx, plugins/clerk-auth/webpack.config.js
Add new plugin - clerk-auth. 
Fixes #71
Create new application in clerk [dashboard](https://dashboard.clerk.com/) and generate the api key for react app. Paste the api key in your .env file and start the application. Once the application loads it asks for signin.
=> add clerk-auth plugin

COUNTRIES.svg
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
=> #77 added COUNTRIES.svg file at the main directory

demo/admin-panel.js, demo/pages/_document.tsx, src/admin/admin-panel.js, webpack.config.js
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
=> Generated a bundle of the admin panel

research/Dynamic_content_forge.md
I've added a new plugin idea. The idea is to add a plugin that can dynamically generate content for a website.
Fixes #84
=> Plugin idea proposal

registry/Webcrumbs_Features.md
Added a list of features that are supported by Webcrumbs
Fixes #80
=> docs: Added a list of features that are supported by webcrumbs

research/Seasonal_Greetings.md
Added documentation for a plugin called Seasonal Greetings
Fixes #36
=> docs: Added documentation for Seasonal Greetings plugin

demo/pages/home/home.module.css, research/API_Endpoints_Research.md
Hello, this is my first draft. 
I believe it contains the required information and steps. 
If there is any feedback please let me know. 
Thanks!
=> finished first draft of WordPress API Endpoint research

research/Blockchain_Security_Plugin.md, research/Chatbot_creation_tool.md, research/best_practices_proposal.md
I've added two ideas for plugin proposals
Fix #81
=> Two plug-in ideas

database/README.md, database/schema/options.json, database/schema/plugins.json, database/schema/posts.json, database/schema/sites.json, database/schema/users.json
This Pull request contains the proposed MongoDB schema. The change, implementation, and details have been explained in the readme.md file as part of the database folder.
Fixes #4 
This is a proposed database design, so at this point, no testing is required as it's an idea or suggestion on how to proceed with the implementation.
=> Webcrumbs Database Proposed Schema

admin/components/login/Login.tsx, admin/context/AuthenticationGuard.tsx, admin/package-lock.json, admin/pages/admin.tsx, admin/pages/auth.jsx, admin/yarn.lock, package-lock.json
Fused the logic of /auth into /login and deleted /auth. Also protected /admin to require /login.
Fixed issue #67 
Fixes #67 (issue)
Tests have been carried out on /login to ensure the UI is not broken while containing the functionality of /auth. Also /admin has been tested to ensure it only loads if there is a current session, although there is currently no way to sign out which is also a needed feature, and every new session lasts for 30 days. I couldn't test what happens if there is no current session because of this but when a new user signing in creates a new session, the session changes showing that it acknowledges the sign-in process.
Add Console.log statements to the AuthenticationGuard Context to view the current session of the admin page, if there is none, you will be redirected …
=> Updated Admin Functionality

CODE_OF_CONDUCT.md, README.md
- Update code of conduct.
- Removing from READ.ME information that are no relevant for the project at the moment
Issue: # (issue number prefixed with #)
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [x ] Any dependent changes have been merged and published in downstream modules
=> Updating Code of Conduct and READ.me

contributions/pricingTable.html
I added a new UI component: Pricing Table. This component provides a clean and responsive layout for displaying different pricing options. It is implemented using HTML and styled with appropriate classes for flexibility and customisation. The pricing table allows for easy comparison between different price tiers, helping users choose the best option.
=> feat: add pricing table ui component

contributions/InputOtpTemplate.html
=> feat: Added 

contributions/search_bar.html
Generated a Search Bar Component with a sleek, magnifying glass icon with neoumorphism effect and an input field for typing and subtle theme.
- **GitHub Username**: [KusumPareek99](https://github.com/KusumPareek99)
[Link to your GitHub repository.](https://github.com/KusumPareek99/webcrumbs)
---
=> feat: added search bar component

contributions/loading.html
Designed an animated loading with a minimalistic design and subtle color transitions for a web application
- **GitHub Username**: [KusumPareek99](https://github.com/KusumPareek99)
[Link to your GitHub repository.](https://github.com/KusumPareek99/webcrumbs)
---
=> feat: added animated loading component

contributions/checkout.html
Checkout UI Component - A simple and interactive checkout UI, ideal for e-commerce platforms or any payment-related processes.
- **GitHub Username**: @mdadul 
[GitHub repository Link.](https://github.com/mdadul/webcrumbs)
=> feat: add checkout UI component

contributions/ImageGalleryTemplate.html
=> feat: Added Image Gallery

contributions/multipleTypeAddFormTemplate.html
A multi-purpose content submission form enabling users to store and categorize links, media, and documents. It can be used in applications like content management systems, bookmarking tools, or collaborative platforms where users need to save and organize different types of information easily.
- **GitHub Username**: [imshubhu](https://github.com/imshubhu)
[Link to your GitHub repository.](https://github.com/imshubhu/webcrumbs/tree/feature/multiple-type-add-form-component)
---
=> feat: multiple type add form template

contributions/resume.html
Resume 
- **GitHub Username**: @mdadul 
[GitHub repository Link.](https://github.com/mdadul/webcrumbs)
=> feat: add portfolio resume component UI

contributions/NotificationHubTemplate.html, contributions/VirtualRealityTemplate.html
=> feat: Added Virtual Reality Template

contributions/dark-mode-landing.html
A dark-themed landing page with glowing text elements and neon accents. Used gradient shadows for depth and incorporates hover animations on buttons.
- **GitHub Username**: [KusumPareek99](https://github.com/KusumPareek99)
[Link to your GitHub repository.](https://github.com/KusumPareek99/webcrumbs)
---
=> Added a landing page with dark mode theme.

contributions/WebToolsTemplate.html, contributions/WorkFlowTemplate.html
=> feat: Added Web Tools Template

contributions/index.html
Social media Dapp Template 
- [ ✅] I confirm that my template is under the MIT license and complies with the Hacktoberfest rules.
- **GitHub Username**: NikhilRaikwar
https://github.com/NikhilRaikwar/webcrumbs
---
=> Added SocialMedia DApp template

contributions/Portfolio.html
Portfolio template
Portfolio website template
-  I confirm that my template is under the MIT license and complies with the Hacktoberfest rules.
- **GitHub Username**: [jisha-jacob]
github.com/jisha-jacob
---
=> Portfolio template

contributions/CollaborationDashboard.html
Real-time Collaboration Dashboard Template
- **GitHub Username**: [AJBrownson]
<h3><a href="https://github.com/AJBrownson/webcrumbs">https://github.com/AJBrownson/webcrumbs</a></h3>
---
=> Add Real-time Collaboration Dashboard template

contributions/signupTemplate.html
Signup
- **GitHub Username**: Daanish2003
[Link to your GitHub repository.](https://github.com/Daanish2003?tab=repositories)
---
=> temp:signup

contributions/resetPasswordTemplate.html
Reset Password
- **GitHub Username**: Daanish2003
https://github.com/Daanish2003?tab=repositories
---
=> temp:reset-password

contributions/forgotPasswordTemplate.html
Forgot password
- **GitHub Username**: Daanish2003
https://github.com/Daanish2003?tab=repositories
---
=> temp:forgot-password

contributions/workspaceTemplate.html
Workspace
- **GitHub Username**: Daanish2003
https://github.com/Daanish2003?tab=repositories
---
=> temp:workspace

contributions/InfographicTemplate.html
=> feat:Added Infographic Template

contributions/ProgressTemplate.html
=> feat: Added ProgressTemplate
